version: '3'

services:
  bienegaessli-cms:
    container_name: bienegaessli-cms
    image: bienegaessli-payload-cms
    build: .
    restart: always
    ports:
      - '3002:3000'
    volumes:
      - ./media:/app/public/media
    depends_on:
      - bienegaessli-mongo
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bienegaessli.rule=Host(`www.golden-vom-bienegässli.de`, `golden-vom-bienegässli.de`)'
      - 'traefik.http.routers.bienegaessli.entrypoints=web, websecure'
      - 'traefik.http.routers.bienegaessli.tls=true'
      - 'traefik.http.routers.bienegaessli.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.bienegaessli.compress=true'
      - 'traefik.http.middlewares.bienegaessli.plugin.httpCache.maxTtl=300'
    networks:
      - bienegaessli_network
      - traefik
    environment:
      DATABASE_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@bienegaessli-mongo:27017/${MONGO_DATABASE}?authSource=admin"
    env_file:
      - .env

  bienegaessli-mongo:
    container_name: bienegaessli-mongo
    image: mongo:4
    ports:
      - '27017:27017'
    restart: always
    command:
      - --storageEngine=wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - ./db-data:/data/db
    networks:
      - bienegaessli_network

networks:
  traefik:
    external: true
  bienegaessli_network:
    driver: bridge
    internal: true
