- name: deploy bienegaessli
  hosts: servers
  gather_facts: no
  tasks:
      - name: Update Git branch
        ansible.builtin.git:
            repo: git@github.com:nstuder/golden-vom-bienegaessli.git
            dest: /home/nstuder/bienegaessli
            version: main
            update: yes

      - name: Create and start services
        community.docker.docker_compose_v2:
            project_src: /home/nstuder/bienegaessli
            build: true
        register: output
